databases:
  - name: heavenly-heights-db
    databaseName: heavenly_heights_resort_production
    user: heavenly_heights_resort
    plan: free
    region: oregon

services:
  - type: web
    name: heavenly-heights-api
    env: ruby
    region: oregon
    plan: free
    buildCommand: "bundle install && bundle exec rake db:migrate && bundle exec rails db:seed"
    startCommand: "bundle exec rails server -e production"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: heavenly-heights-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    autoDeploy: true

  - type: web
    name: heavenly-heights-resort
    runtime: static
    envVars:
      - key: VITE_RAILS_BASE_URL
        fromService:
          type: web
          name: heavenly-heights-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: WEB_CONCURRENCY
        sync: false
      - key: VITE_CLOUDINARY_CLOUD_NAME
        fromService:
          type: web
          name: heavenly-heights-api
          envVarKey: CLOUDINARY_CLOUD_NAME
    buildCommand: npm install; npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    rootDir: client
    pullRequestPreviewsEnabled: false

version: "1"
